services:
  - type: web
    name: pose-estimation
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
